apiVersion: v1
kind: Namespace
metadata:
  name: kuma
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  namespace: kuma
  labels:
    app: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: docker.io/louislam/uptime-kuma:latest
        ports:
        - containerPort: 3001
          protocol: TCP
        env:
        - name: UPTIME_KUME_PORT
          value: "3001"
        - name: PORT
          value: "3001"
        volumeMounts:
        - name: uptime-kuma
          mountPath: /app/data
      volumes:
      - name: uptime-kuma
        persistentVolumeClaim:
          claimName: uptime-kuma
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: kuma
spec:
  selector:
    app: uptime-kuma
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma
  namespace: kuma
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

