apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Kunde100/Kunde-k8s.git
    targetRevision: HEAD
    path: prod/cloudflared/
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
