apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuma-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Kunde100/Kunde-k8s.git
    targetRevision: HEAD
    path: prod/kuma
  destination:
    server: https://kubernetes.default.svc
    namespace: kuma
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
