apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:kyrbrbik/kubernetes.git
    targetRevision: HEAD
    path: prod/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 45.2.0
    helm:
      valueFiles:
      - $values/prod/prometheus/values.yml
  - repoURL: git@github.com:kyrbrbik/kubernetes.git
    targetRevision: main
    ref: values
  destination:      
    server: https://kubernetes.default.svc
    namespace: monitoring

