apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voice-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:kyrbrbik/kubernetes.git
    targetRevision: HEAD
    path: prod/Voice-app/
  destination:
    server: https://kubernetes.default.svc
    namespace: voice
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
